workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_secrets
      flutter: stable
      java: 17
    scripts:
      - name: Generate .env file
        script: |
          echo "GROQ_API_KEY=$GROQ_API_KEY" > .env
          echo "ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk

  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_secrets
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate .env file
        script: |
          echo "GROQ_API_KEY=$GROQ_API_KEY" > .env
          echo "ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/mapping.txt
